import uuid
from typing import Optional
from datetime import datetime, timezone
from sqlalchemy import Column, String, Text, DateTime, Integer, Float, ForeignKey, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.dialects.postgresql import UUID

from app.models.base import Base


class Job(Base):
    """
    Represents an open job requisition discovered online (e.g. scraped from LinkedIn).
    """
    __tablename__ = "jobs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    company_name = Column(String, index=True, nullable=False)
    role_title = Column(String, index=True, nullable=False)
    description = Column(Text, nullable=False)
    location = Column(String, nullable=True)
    salary_range = Column(String, nullable=True)
    job_url = Column(String, nullable=False, unique=True, index=True)
    
    # Matching Intelligence properties
    match_score = Column(Float, nullable=True) # Percentage match (0.0 - 100.0) generated by AI
    
    posted_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
    
    # Relationships
    applications = relationship("Application", back_populates="job", cascade="all, delete-orphan")


class Resume(Base):
    """
    Represents a user's uploaded Resume PDF text structure.
    In a real system, we'd store the raw S3 bucket URL here along with extracted metadata.
    """
    __tablename__ = "resumes"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    
    file_name = Column(String, nullable=False)
    raw_text = Column(Text, nullable=False) # Extracted OCR/PDF content
    
    uploaded_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)


class Application(Base):
    """
    Associates a User to a specific Job tracking their CRM Kanban status.
    Stores contextual artifacts like custom generated Cover Letters.
    """
    __tablename__ = "applications"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    job_id = Column(UUID(as_uuid=True), ForeignKey("jobs.id", ondelete="CASCADE"), nullable=False)
    resume_id = Column(UUID(as_uuid=True), ForeignKey("resumes.id", ondelete="SET NULL"), nullable=True)
    
    status = Column(String, nullable=False, default="saved") # "saved", "applied", "interviewing", "rejected"
    
    # Contextual artifacts
    ai_cover_letter = Column(Text, nullable=True)
    ai_tailored_resume_json = Column(JSON, nullable=True) # Pydantic output from Resume Optimizer
    
    applied_at = Column(DateTime, nullable=True)

    # Relationships
    job = relationship("Job", back_populates="applications")
