from datetime import datetime, timezone
import uuid
from sqlalchemy import String, DateTime, Text, Integer, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.models.base import Base

class TargetAccount(Base):
    """
    Represents an Enterprise B2B Account the user is targeting.
    """
    __tablename__ = "target_accounts"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), index=True)
    
    company_name: Mapped[str] = mapped_column(String)
    industry: Mapped[str] = mapped_column(String)
    employee_count: Mapped[str] = mapped_column(String, nullable=True)
    domain: Mapped[str] = mapped_column(String, nullable=True)
    
    # State tracking
    abm_status: Mapped[str] = mapped_column(String, default="watching") # watching, campaigning, meeting, closed
    
    created_at: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

class CompanySignal(Base):
    """
    Represents a trigger event (e.g., funding round, leadership change).
    """
    __tablename__ = "company_signals"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    account_id: Mapped[str] = mapped_column(String, ForeignKey("target_accounts.id"), index=True)
    
    signal_type: Mapped[str] = mapped_column(String) # e.g. "leadership_change", "funding_round"
    signal_description: Mapped[str] = mapped_column(Text)
    mapped_pain_point: Mapped[str] = mapped_column(Text, nullable=True) # Generated by AI Copilot
    
    discovered_at: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(timezone.utc))

class Campaign(Base):
    """
    Represents a multi-touch outreach campaign targeting a specific account.
    """
    __tablename__ = "campaigns"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    account_id: Mapped[str] = mapped_column(String, ForeignKey("target_accounts.id"), index=True)
    
    name: Mapped[str] = mapped_column(String)
    status: Mapped[str] = mapped_column(String, default="drafting") # drafting, active, completed, paused
    
    created_at: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

class SequenceStep(Base):
    """
    Represents drafted generative messages belonging to a Campaign.
    """
    __tablename__ = "sequence_steps"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    campaign_id: Mapped[str] = mapped_column(String, ForeignKey("campaigns.id"), index=True)
    
    step_order: Mapped[int] = mapped_column(Integer)
    subject: Mapped[str] = mapped_column(String, nullable=True)
    body: Mapped[str] = mapped_column(Text)
    status: Mapped[str] = mapped_column(String, default="pending") # pending, sent, replied
    send_date: Mapped[datetime] = mapped_column(DateTime, nullable=True)
