"""0001_initial_schema

Revision ID: 0d3492c3c9ab
Revises: 
Create Date: 2026-04-05 01:32:20.231163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d3492c3c9ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_feedbacks',
    sa.Column('post_id', sa.String(length=100), nullable=True),
    sa.Column('original_generated_comment', sa.Text(), nullable=False),
    sa.Column('final_user_edited_comment', sa.Text(), nullable=True),
    sa.Column('was_used', sa.Boolean(), nullable=False),
    sa.Column('engagement_likes', sa.Integer(), nullable=False),
    sa.Column('engagement_replies', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp. Non-null = deleted.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_feedbacks_post_id'), 'comment_feedbacks', ['post_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('salary_range', sa.String(), nullable=True),
    sa.Column('job_url', sa.String(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_company_name'), 'jobs', ['company_name'], unique=False)
    op.create_index(op.f('ix_jobs_job_url'), 'jobs', ['job_url'], unique=True)
    op.create_index(op.f('ix_jobs_role_title'), 'jobs', ['role_title'], unique=False)
    op.create_table('oauth_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state_token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='Set for write-flow; NULL for read-flow'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_states_state_token'), 'oauth_states', ['state_token'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('linkedin_id', sa.String(length=100), nullable=False),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('write_access_token_encrypted', sa.Text(), nullable=True, comment='LinkedIn write-flow OAuth access token'),
    sa.Column('li_at_cookie_encrypted', sa.Text(), nullable=True, comment='Browser session cookie for Playwright scraper'),
    sa.Column('linkedin_person_id', sa.String(length=100), nullable=True, comment='LinkedIn numeric person ID for urn:li:person: URN'),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp. Non-null = deleted.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_linkedin_id'), 'users', ['linkedin_id'], unique=True)
    op.create_index(op.f('ix_users_linkedin_person_id'), 'users', ['linkedin_person_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('current_role', sa.String(), nullable=False),
    sa.Column('current_company', sa.String(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('ats_status', sa.String(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_user_id'), 'candidates', ['user_id'], unique=False)
    op.create_table('posts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('body_content', sa.Text(), nullable=False),
    sa.Column('call_to_action', sa.Text(), nullable=False),
    sa.Column('final_content', sa.Text(), nullable=True, comment='User-edited merged content'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='draft | approved | published | archived'),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('audience', sa.String(length=100), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True, comment='When this should be auto-published'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='When this was published or simulated published'),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='LLM model, tokens used, latency, prompt version'),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('virality_score', sa.Integer(), nullable=True, comment='AI-predicted virality score 0-100. Set on draft creation.'),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Breakdown: {hook_strength, readability, value_density, cta_quality}'),
    sa.Column('hook_alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of [{hook, predicted_score}] alternatives generated by AI'),
    sa.Column('actual_engagement_rate', sa.Integer(), nullable=True, comment='Actual post-publish engagement rate * 1000 (stored as integer for indexing)'),
    sa.Column('score_updated_at', sa.DateTime(), nullable=True, comment='When virality_score was last calculated or recalibrated'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp. Non-null = deleted.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_table('prospects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('intent_score', sa.Integer(), nullable=False),
    sa.Column('buying_signal', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospects_id'), 'prospects', ['id'], unique=False)
    op.create_index(op.f('ix_prospects_user_id'), 'prospects', ['user_id'], unique=False)
    op.create_table('requisitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requisitions_user_id'), 'requisitions', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shadow_action_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('ai_draft_content', sa.Text(), nullable=False),
    sa.Column('human_final_content', sa.Text(), nullable=False),
    sa.Column('edit_similarity_score', sa.Float(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shadow_action_logs_user_id'), 'shadow_action_logs', ['user_id'], unique=False)
    op.create_table('target_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('employee_count', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('abm_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_accounts_user_id'), 'target_accounts', ['user_id'], unique=False)
    op.create_table('tracked_creators',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('linkedin_id', sa.String(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('auto_generation_prompt', sa.String(), nullable=True, comment='Custom instructions for when this creator posts'),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp. Non-null = deleted.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_creators_user_id'), 'tracked_creators', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=True, comment='Hex color used as carousel card background accent (#rrggbb)'),
    sa.Column('logo_url', sa.Text(), nullable=True, comment='URL of user/company logo used on carousel slides'),
    sa.Column('font_family', sa.String(length=100), nullable=True, comment='Google Font name for carousel text rendering'),
    sa.Column('author_name', sa.String(length=200), nullable=True, comment='Display name shown on carousel footer'),
    sa.Column('author_tagline', sa.String(length=300), nullable=True, comment='One-line tagline under name on carousel footer'),
    sa.Column('pillars', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Saved content pillars for Smart Fill'),
    sa.Column('posts_per_week', sa.Integer(), nullable=True),
    sa.Column('preferred_formats', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='["text","carousel","video"]'),
    sa.Column('auto_score_drafts', sa.Boolean(), nullable=False, comment='Auto virality-score posts on creation'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp. Non-null = deleted.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ai_cover_letter', sa.Text(), nullable=True),
    sa.Column('ai_tailored_resume_json', sa.JSON(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['target_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_account_id'), 'campaigns', ['account_id'], unique=False)
    op.create_table('carousel_assets',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('slides_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='[{slide_number, headline, body, visual_suggestion}]'),
    sa.Column('pdf_url', sa.Text(), nullable=True, comment='GCS/local URL of rendered PDF'),
    sa.Column('slide_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, comment='draft | rendered | published'),
    sa.Column('linkedin_asset_urn', sa.Text(), nullable=True, comment='urn:li:document:... — returned by LinkedIn after upload'),
    sa.Column('brand_kit_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Snapshot of brand_kit at render time: {primary_color, logo_url, font}'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp. Non-null = deleted.'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carousel_assets_post_id'), 'carousel_assets', ['post_id'], unique=False)
    op.create_table('company_signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('signal_description', sa.Text(), nullable=False),
    sa.Column('mapped_pain_point', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['target_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_signals_account_id'), 'company_signals', ['account_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prospect_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('initial_message_draft', sa.Text(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_prospect_id'), 'conversations', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('engagers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('linkedin_id', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('interaction_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingested_posts',
    sa.Column('tracked_creator_id', sa.UUID(), nullable=False),
    sa.Column('linkedin_post_id', sa.String(), nullable=False),
    sa.Column('post_url', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('reposts', sa.Integer(), nullable=True, comment='Number of reposts/reshares — populated by appium read flow or enrichment'),
    sa.Column('ingestion_source', sa.String(length=50), nullable=True, comment='scheduled | direct | appium'),
    sa.Column('is_processed', sa.Integer(), nullable=True, comment='1 if AI has generated comment drafts for this post'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp. Non-null = deleted.'),
    sa.ForeignKeyConstraint(['tracked_creator_id'], ['tracked_creators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingested_posts_linkedin_post_id'), 'ingested_posts', ['linkedin_post_id'], unique=True)
    op.create_index(op.f('ix_ingested_posts_posted_at'), 'ingested_posts', ['posted_at'], unique=False)
    op.create_index(op.f('ix_ingested_posts_tracked_creator_id'), 'ingested_posts', ['tracked_creator_id'], unique=False)
    op.create_table('llm_evaluations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('hallucination_score', sa.Integer(), nullable=False),
    sa.Column('tone_adherence_score', sa.Integer(), nullable=False),
    sa.Column('safety_compliance_score', sa.Integer(), nullable=False),
    sa.Column('judge_rationale', sa.Text(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['shadow_action_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_evaluations_log_id'), 'llm_evaluations', ['log_id'], unique=False)
    op.create_table('post_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_drafts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ingested_post_id', sa.UUID(), nullable=False),
    sa.Column('insightful_content', sa.Text(), nullable=False),
    sa.Column('contrarian_content', sa.Text(), nullable=False),
    sa.Column('supportive_content', sa.Text(), nullable=False),
    sa.Column('selected_strategy', sa.String(length=50), nullable=True, comment='insightful | contrarian | supportive'),
    sa.Column('final_content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='draft | copied | published | archived'),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp. Non-null = deleted.'),
    sa.ForeignKeyConstraint(['ingested_post_id'], ['ingested_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_drafts_status'), 'comment_drafts', ['status'], unique=False)
    op.create_index(op.f('ix_comment_drafts_user_id'), 'comment_drafts', ['user_id'], unique=False)
    op.create_table('engager_classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engager_id', sa.UUID(), nullable=False),
    sa.Column('persona', sa.String(), nullable=False),
    sa.Column('classified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engager_id'], ['engagers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engager_id')
    )
    op.create_table('sequence_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('send_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequence_steps_campaign_id'), 'sequence_steps', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sequence_steps_campaign_id'), table_name='sequence_steps')
    op.drop_table('sequence_steps')
    op.drop_table('engager_classifications')
    op.drop_index(op.f('ix_comment_drafts_user_id'), table_name='comment_drafts')
    op.drop_index(op.f('ix_comment_drafts_status'), table_name='comment_drafts')
    op.drop_table('comment_drafts')
    op.drop_table('post_metrics')
    op.drop_index(op.f('ix_llm_evaluations_log_id'), table_name='llm_evaluations')
    op.drop_table('llm_evaluations')
    op.drop_index(op.f('ix_ingested_posts_tracked_creator_id'), table_name='ingested_posts')
    op.drop_index(op.f('ix_ingested_posts_posted_at'), table_name='ingested_posts')
    op.drop_index(op.f('ix_ingested_posts_linkedin_post_id'), table_name='ingested_posts')
    op.drop_table('ingested_posts')
    op.drop_table('engagers')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_prospect_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_company_signals_account_id'), table_name='company_signals')
    op.drop_table('company_signals')
    op.drop_index(op.f('ix_carousel_assets_post_id'), table_name='carousel_assets')
    op.drop_table('carousel_assets')
    op.drop_index(op.f('ix_campaigns_account_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('applications')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_tracked_creators_user_id'), table_name='tracked_creators')
    op.drop_table('tracked_creators')
    op.drop_index(op.f('ix_target_accounts_user_id'), table_name='target_accounts')
    op.drop_table('target_accounts')
    op.drop_index(op.f('ix_shadow_action_logs_user_id'), table_name='shadow_action_logs')
    op.drop_table('shadow_action_logs')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_requisitions_user_id'), table_name='requisitions')
    op.drop_table('requisitions')
    op.drop_index(op.f('ix_prospects_user_id'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_id'), table_name='prospects')
    op.drop_table('prospects')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_candidates_user_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_users_linkedin_person_id'), table_name='users')
    op.drop_index(op.f('ix_users_linkedin_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_oauth_states_state_token'), table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index(op.f('ix_jobs_role_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_url'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_name'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_comment_feedbacks_post_id'), table_name='comment_feedbacks')
    op.drop_table('comment_feedbacks')
    # ### end Alembic commands ###
