"""baseline_schema

Revision ID: db7d4578f901
Revises: 
Create Date: 2026-04-04 20:52:09.346322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7d4578f901'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state_token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='Set for write-flow; NULL for read-flow'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_states_state_token'), 'oauth_states', ['state_token'], unique=True)
    op.drop_constraint(op.f('shadow_action_logs_user_id_fkey'), 'shadow_action_logs', type_='foreignkey')
    op.create_foreign_key(None, 'shadow_action_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shadow_action_logs', type_='foreignkey')
    op.create_foreign_key(op.f('shadow_action_logs_user_id_fkey'), 'shadow_action_logs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_oauth_states_state_token'), table_name='oauth_states')
    op.drop_table('oauth_states')
    # ### end Alembic commands ###
