"""
Pydantic schemas for the Creator Radar and Comment Copilot features.
"""

from datetime import datetime
from uuid import UUID
from pydantic import BaseModel, HttpUrl, Field


# --- Tracked Creator Schemas ---

class TrackedCreatorCreate(BaseModel):
    """Payload to start monitoring a new creator."""
    linkedin_id: str | None = None
    profile_url: HttpUrl
    full_name: str | None = None
    headline: str | None = None
    profile_picture_url: HttpUrl | None = None
    auto_generation_prompt: str | None = None


class TrackedCreatorResponse(BaseModel):
    """Creator representation returned to frontend."""
    id: UUID
    linkedin_id: str
    profile_url: HttpUrl
    full_name: str
    headline: str | None
    profile_picture_url: HttpUrl | None
    auto_generation_prompt: str | None
    is_active: int
    created_at: datetime

    model_config = {"from_attributes": True}


# --- Ingested Post Schemas ---

class IngestedPostResponse(BaseModel):
    """A scraped post from a tracked creator."""
    id: UUID
    tracked_creator_id: UUID
    linkedin_post_id: str
    post_url: HttpUrl
    content: str
    posted_at: datetime
    likes: int
    comments: int
    ingestion_source: str
    is_processed: int
    created_at: datetime

    model_config = {"from_attributes": True}


# --- Comment Draft Schemas ---

class CommentGenerateRequest(BaseModel):
    """Trigger AI comment generation for a specific ingested post."""
    ingested_post_id: UUID


class CommentDraftResponse(BaseModel):
    """The 3 strategy drafts generated by the AI Engine."""
    id: UUID
    ingested_post_id: UUID
    insightful_content: str
    contrarian_content: str
    supportive_content: str
    selected_strategy: str | None
    final_content: str | None
    status: str
    created_at: datetime

    model_config = {"from_attributes": True}


class CommentDraftUpdateRequest(BaseModel):
    """Payload for the 'Copy & Go' flow where user selects/edits a draft."""
    selected_strategy: str | None = Field(None, description="insightful | contrarian | supportive")
    final_content: str | None = None
    status: str | None = Field(None, description="draft | copied | published | archived")
