"""
Migration script — add virality scoring columns to posts table.
Safe to run multiple times (uses IF NOT EXISTS).

Run from core_api root:
    python -m scripts.migrate_virality_columns
"""
import asyncio
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy import text
from app.config import get_settings


MIGRATION_SQL = """
DO $$
BEGIN
    -- virality_score
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'posts' AND column_name = 'virality_score'
    ) THEN
        ALTER TABLE posts ADD COLUMN virality_score INTEGER;
        COMMENT ON COLUMN posts.virality_score IS 'AI-predicted virality score 0-100. Set on draft scoring.';
    END IF;

    -- score_breakdown
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'posts' AND column_name = 'score_breakdown'
    ) THEN
        ALTER TABLE posts ADD COLUMN score_breakdown JSONB;
        COMMENT ON COLUMN posts.score_breakdown IS 'Breakdown: {hook_strength, readability, value_density, cta_quality}';
    END IF;

    -- hook_alternatives
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'posts' AND column_name = 'hook_alternatives'
    ) THEN
        ALTER TABLE posts ADD COLUMN hook_alternatives JSONB;
        COMMENT ON COLUMN posts.hook_alternatives IS 'List of [{hook, predicted_score}] alternatives generated by AI';
    END IF;

    -- actual_engagement_rate
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'posts' AND column_name = 'actual_engagement_rate'
    ) THEN
        ALTER TABLE posts ADD COLUMN actual_engagement_rate INTEGER;
        COMMENT ON COLUMN posts.actual_engagement_rate IS 'Actual post-publish engagement rate * 1000 (stored as integer for indexing)';
    END IF;

    -- score_updated_at
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'posts' AND column_name = 'score_updated_at'
    ) THEN
        ALTER TABLE posts ADD COLUMN score_updated_at TIMESTAMP;
        COMMENT ON COLUMN posts.score_updated_at IS 'When virality_score was last calculated or recalibrated';
    END IF;
END;
$$;
"""


async def run():
    settings = get_settings()
    engine = create_async_engine(settings.database_url, echo=True)
    async with engine.begin() as conn:
        await conn.execute(text(MIGRATION_SQL))
    await engine.dispose()
    print("✅ Virality columns migration complete.")


if __name__ == "__main__":
    asyncio.run(run())
